const char* labels[] = {
"",       // KC_NO
(const char*)-1,      // KC_TRANSPARENT
0,       // 0x02
0,       // 0x03
"A",     // KC_A
"B",     // KC_B
"C",     // KC_C
"D",     // KC_D
"E",     // KC_E
"F",     // KC_F
"G",     // KC_G
"H",     // KC_H
"I",     // KC_I
"J",     // KC_J
"K",     // KC_K
"L",     // KC_L
"M",     // KC_M
"N",     // KC_N
"O",     // KC_O
"P",     // KC_P
"Q",     // KC_Q
"R",     // KC_R
"S",     // KC_S
"T",     // KC_T
"U",     // KC_U
"V",     // KC_V
"W",     // KC_W
"X",     // KC_X
"Y",     // KC_Y
"Z",     // KC_Z
"1",     // KC_1
"2",     // KC_2
"3",     // KC_3
"4",     // KC_4
"5",     // KC_5
"6",     // KC_6
"7",     // KC_7
"8",     // KC_8
"9",     // KC_9
"0",     // KC_0
"Enter", // KC_ENTER
"Esc",   // KC_ESCAPE
"Bcksp", // KC_BACKSPACE
"Tab",   // KC_TAB
"Space", // KC_SPACE
"-",     // KC_MINUS
"=",     // KC_EQUAL
"[",     // KC_LEFT_BRACKET
"]",     // KC_RIGHT_BRACKET
"\\",    // KC_BACKSLASH
"#",     // KC_NONUS_HASH
";",     // KC_SEMICOLON
"\'",    // KC_QUOTE
"`",     // KC_GRAVE
",",     // KC_COMMA
".",     // KC_DOT
"/",     // KC_SLASH
"Caps",  // KC_CAPS_LOCK
"F1",    // KC_F1
"F2",    // KC_F2
"F3",    // KC_F3
"F4",    // KC_F4
"F5",    // KC_F5
"F6",    // KC_F6
"F7",    // KC_F7
"F8",    // KC_F8
"F9",    // KC_F9
"F10",   // KC_F10
"F11",   // KC_F11
"F12",   // KC_F12
"PrScr", // KC_PRINT_SCREEN
"ScrLk", // KC_SCROLL_LOCK
"Pause", // KC_PAUSE
"Ins",   // KC_INSERT
"Home",  // KC_HOME
"PgUp",  // KC_PAGE_UP
"Del",   // KC_DELETE
"End",   // KC_END
"PgDn",  // KC_PAGE_DOWN
"Right", // KC_RIGHT
"Left",  // KC_LEFT
"Down",  // KC_DOWN
"Up",    // KC_UP
"NumLk", // KC_NUM_LOCK
"/",     // KC_KP_SLASH
"*",     // KC_KP_ASTERISK
"-",     // KC_KP_MINUS
"+",     // KC_KP_PLUS
"Enter", // KC_KP_ENTER
"1",     // KC_KP_1
"2",     // KC_KP_2
"3",     // KC_KP_3
"4",     // KC_KP_4
"5",     // KC_KP_5
"6",     // KC_KP_6
"7",     // KC_KP_7
"8",     // KC_KP_8
"9",     // KC_KP_9
"0",     // KC_KP_0
".",     // KC_KP_DOT
"\\",    // KC_NONUS_BACKSLASH
"App",   // KC_APPLICATION
"App",   // KC_KB_POWER
"=",     // KC_KP_EQUAL
"F13",   // KC_F13
"F14",   // KC_F14
"F15",   // KC_F15
"F16",   // KC_F16
"F17",   // KC_F17
"F18",   // KC_F18
"F19",   // KC_F19
"F20",   // KC_F20
"F21",   // KC_F21
"F22",   // KC_F22
"F23",   // KC_F23
"F24",   // KC_F24
"Exe",   // KC_EXECUTE
"Help",  // KC_HELP
"Menu",  // KC_MENU
"Sel",   // KC_SELECT
"Stop",  // KC_STOP
"Again", // KC_AGAIN
"Undo",  // KC_UNDO
"Cut",   // KC_CUT
"Copy",  // KC_COPY
"Paste", // KC_PASTE
"Find",  // KC_FIND
"Mute",  // KC_KB_MUTE
"Vol+",  // KC_KB_VOLUME_UP
"Vol-",  // KC_KB_VOLUME_DOWN
"Caps",  // KC_LOCKING_CAPS_LOCK
"NumLk", // KC_LOCKING_NUM_LOCK
"ScrLk", // KC_LOCKING_SCROLL_LOCK
",",     // KC_KP_COMMA
"=",     // KC_KP_EQUAL_AS400
"INT 1", // KC_INTERNATIONAL_1
"INT 2", // KC_INTERNATIONAL_2
"INT 3", // KC_INTERNATIONAL_3
"INT 4", // KC_INTERNATIONAL_4
"INT 5", // KC_INTERNATIONAL_5
"INT 6", // KC_INTERNATIONAL_6
"INT 7", // KC_INTERNATIONAL_7
"INT 8", // KC_INTERNATIONAL_8
"INT 9", // KC_INTERNATIONAL_9
"LANG1", // KC_LANGUAGE_1
"LANG2", // KC_LANGUAGE_2
"LANG3", // KC_LANGUAGE_3
"LANG4", // KC_LANGUAGE_4
"LANG5", // KC_LANGUAGE_5
"LANG6", // KC_LANGUAGE_6
"LANG7", // KC_LANGUAGE_7
"LANG8", // KC_LANGUAGE_8
"LANG9", // KC_LANGUAGE_9
"AltEr", // KC_ALTERNATE_ERASE
"SysRq", // KC_SYSTEM_REQUEST
"Cancl", // KC_CANCEL
"Clear", // KC_CLEAR
"Prior", // KC_PRIOR
"Retrn", // KC_RETURN
"Seprt", // KC_SEPARATOR
"Out",   // KC_OUT
"Oper",  // KC_OPER
"Clear", // KC_CLEAR_AGAIN
"CrSel", // KC_CRSEL
"ExSel", // KC_EXSEL
"PwrDn", // KC_SYSTEM_POWER
"Sleep", // KC_SYSTEM_SLEEP
"Wake",  // KC_SYSTEM_WAKE
"Mute",  // KC_AUDIO_MUTE
"Vol+",  // KC_AUDIO_VOL_UP
"Vol-",  // KC_AUDIO_VOL_DOWN
"Next",  // KC_MEDIA_NEXT_TRACK
"Prev",  // KC_MEDIA_PREV_TRACK
"Stop",  // KC_MEDIA_STOP
"Play",  // KC_MEDIA_PLAY_PAUSE
"Playr", // KC_MEDIA_SELECT
"Eject", // KC_MEDIA_EJECT
"Mail",  // KC_MAIL
"Calc",  // KC_CALCULATOR
"MComp", // KC_MY_COMPUTER
"BSrch", // KC_WWW_SEARCH
"BHome", // KC_WWW_HOME
"BBack", // KC_WWW_BACK
"BFwd",  // KC_WWW_FORWARD
"BStop", // KC_WWW_STOP
"BRfsh", // KC_WWW_REFRESH
"BFav",  // KC_WWW_FAVORITES
"NTrck", // KC_MEDIA_FAST_FORWARD
"PTrck", // KC_MEDIA_REWIND
"Brgt+", // KC_BRIGHTNESS_UP
"Brgt-", // KC_BRIGHTNESS_DOWN
"CtrPn", // KC_CONTROL_PANEL
"Assis", // KC_ASSISTANT
0,       // 0xc1
0,       // 0xc2
0,       // 0xc3
0,       // 0xc4
0,       // 0xc5
0,       // 0xc6
0,       // 0xc7
0,       // 0xc8
0,       // 0xc9
0,       // 0xca
0,       // 0xcb
0,       // 0xcc
"MsUp",  // KC_MS_UP
"MsDn",  // KC_MS_DOWN
"MsL",   // KC_MS_LEFT
"MsR",   // KC_MS_RIGHT
"MsB1",  // KC_MS_BTN1
"MsB2",  // KC_MS_BTN2
"MsB3",  // KC_MS_BTN3
"MsB4",  // KC_MS_BTN4
"MsB5",  // KC_MS_BTN5
"MsB6",  // KC_MS_BTN6
"MsB7",  // KC_MS_BTN7
"MsB8",  // KC_MS_BTN8
"WhlUp", // KC_MS_WH_UP
"WhlDn", // KC_MS_WH_DOWN
"WhlL",  // KC_MS_WH_LEFT
"WhlR",  // KC_MS_WH_RIGHT
"Spd0",  // KC_MS_ACCEL0
"Spd1",  // KC_MS_ACCEL1
"Spd2",  // KC_MS_ACCEL2
"Ctrl",  // KC_LEFT_CTRL
"Shift", // KC_LEFT_SHIFT
"Alt",   // KC_LEFT_ALT
"GUI",   // KC_LEFT_GUI
"Ctrl",  // KC_RIGHT_CTRL
"Shift", // KC_RIGHT_SHIFT
"Alt",   // KC_RIGHT_ALT
"GUI",   // KC_RIGHT_GUI
0,       // 0xe8
0,       // 0xe9
0,       // 0xea
0,       // 0xeb
0,       // 0xec
0,       // 0xed
0,       // 0xee
0,       // 0xef
0,       // 0xf0
0,       // 0xf1
0,       // 0xf2
0,       // 0xf3
0,       // 0xf4
0,       // 0xf5
0,       // 0xf6
0,       // 0xf7
0,       // 0xf8
0,       // 0xf9
0,       // 0xfa
0,       // 0xfb
0,       // 0xfc
0,       // 0xfd
0,       // 0xfe
0,       // 0xff
};
