#define ANALOG_JOYSTICK_X_AXIS_PIN GP28
#define ANALOG_JOYSTICK_Y_AXIS_PIN GP29
#define POINTING_DEVICE_INVERT_Y
// #define POINTING_DEVICE_INVERT_X
#define ANALOG_JOYSTICK_AUTO_AXIS 1
#define ANALOG_JOYSTICK_CLICK_PIN GP27
