#pragma once

#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_LED GP25
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_TIMEOUT 500U

#define I2C_DRIVER    I2CD1
#define I2C1_SCL_PIN  GP15
#define I2C1_SDA_PIN  GP14

#define ANALOG_JOYSTICK_X_AXIS_PIN GP28
#define ANALOG_JOYSTICK_Y_AXIS_PIN GP29
#define POINTING_DEVICE_INVERT_Y
// #define POINTING_DEVICE_INVERT_X
#define ANALOG_JOYSTICK_AUTO_AXIS 1
#define ANALOG_JOYSTICK_CLICK_PIN GP27

#define QUANTUM_PAINTER_DISPLAY_TIMEOUT 0
